### ISSUE TITLE
installing 7.7.16 fails on MacOS X

### ISSUE THREAD

**Issue by xoltar** [fnogatz/swivm#10]
After applying the workaround in #9, attempted installation of 7.7.16. Last message is:

```
ERROR: The following packages.failed.install: ssl
readline
bdb
```

Scrolling back through the buffer, I see:

```
readline4pl.c:604:5: error: use of undeclared identifier 'rl_catch_signals'
  { rl_catch_signals = 0;
    ^
```

and

```
ssl4pl.c:42:10: fatal error: 'openssl/rand.h' file not found
#include <openssl/rand.h>
         ^~~~~~~~~~~~~~~~
```

And looking even further back, it appears the configuration noticed there were problems, it probably should have stopped there instead of trying to build. Some of these packages (e.g. bdb) don't have easily identified brew packages that would provide them, and others (openssl) seem to already be installed, but are not recognized. Maybe I'm the first person to try installing this on a Mac?

Any suggestions welcome.

Thanks!

```
% Checking your SWI-Prolog kit for common issues ...
% 
% Version: ............. 7.7.16
% Address bits: ........ 64
% Architecture: ........ x86_64-darwin17.6.0
% Installed at: ........ /Users/bkeller/.swivm/versions/7.7.16/lib/swipl-7.7.16
% Cores: ............... 8
% 
% Checking gmp ................................. ok
Warning: library(archive) ...................... NOT FOUND
Warning: See http://www.swi-prolog.org/build/issues/archive.html
% Loading library(cgi) ......................... ok
% Loading library(crypt) ....................... ok
Warning: library(bdb) .......................... NOT FOUND
Warning: See http://www.swi-prolog.org/build/issues/bdb.html
% Loading library(double_metaphone) ............ ok
% Loading library(filesex) ..................... ok
% Loading library(http/http_stream) ............ ok
% Loading library(http/json) ................... ok
% Loading library(http/jquery) ................. ok
%   jQuery from /Users/bkeller/.swivm/versions/7.7.16/lib/swipl-7.7.16/library/http/web/js/jquery-1.11.3.min.js
% Loading library(isub) ........................ ok
% Loading library(jpl) ......................... FAILED
Warning: Cannot load required shared library
Warning: See http://www.swi-prolog.org/build/issues/jpl.html
% Loading library(memfile) ..................... ok
Warning: library(odbc) ......................... NOT FOUND
Warning: See http://www.swi-prolog.org/build/issues/odbc.html
% Loading library(pce) ......................... ok
% Loading library(pcre) ........................ ok
% Loading library(pdt_console) ................. ok
% Loading library(porter_stem) ................. ok
% Loading library(process) ..................... ok
% Loading library(editline) .................... ok
Warning: library(readline) ..................... NOT FOUND
Warning: See http://www.swi-prolog.org/build/issues/readline.html
% Loading library(readutil) .................... ok
% Loading library(rlimit) ...................... ok
% Loading library(semweb/rdf_db) ............... ok
% Loading library(semweb/rdf_ntriples) ......... ok
% Loading library(semweb/turtle) ............... ok
% Loading library(sgml) ........................ ok
% Loading library(sha) ......................... ok
% Loading library(snowball) .................... ok
% Loading library(socket) ...................... ok
Warning: library(ssl) .......................... NOT FOUND
Warning: See http://www.swi-prolog.org/build/issues/ssl.html
% Loading library(syslog) ...................... ok
% Loading library(table) ....................... ok
% Loading library(time) ........................ ok
% Loading library(unicode) ..................... ok
% Loading library(uri) ......................... ok
Warning: library(uuid) ......................... NOT FOUND
Warning: See http://www.swi-prolog.org/build/issues/uuid.html
% Loading library(zlib) ........................ ok
% Loading library(yaml) ........................ ok
Warning: Could not find swipl on $PATH. 
Warning: You may wish to add '/Users/bkeller/.swivm/versions/7.7.16/bin' to $PATH. 
Warning: Found 7 issues.

QA Notice: Package triggers severe warnings which indicate that it
           may exhibit random runtime failures.

```

**Comment by Anniepoo** [comment]
Your install is actually fine - it's just missing some obscure library support we're unlikely to use.
You have editline - ignore the readline message.
archive - ignore, only needed to read/write tarballs.
bdb - ignore, only needed for Berkeley Database support
jpl - ignore, this is the Java-Prolog bridge.
odbc - ignore, this is support for ODBC database connections.
ssl - ignore, though you might wish to correct it for web development.
uuid - you should probably correct that some day. You'll be fine if you want to put it off a while, just won't have uuid's.
try
emacs.
at the ?- prompt to make sure your X install is good.
If you get a little editor, you're good to go. 
halt.
exits
note periods on end of those.

**Comment by fnogatz** [comment]
As @Anniepoo said: Your installation is actually working, just some libraries are missing. This could be fixed by ensuring that you installed all the dependencies as stated in the [README](https://github.com/fnogatz/swivm#installation).

Would you prefer the default behaviour to stop the installation when there are failing installations of optional libraries?

**Comment by Anniepoo** [comment]
I'd discourage that being the default behavior. It's very very common to have missing dependencies in SWI-Prolog. bdb, odbc, readline, and jpl in particular. Readline inclusion gpl's one's installation, so that's particularly often.
Perhaps we should modify check_installation to provide more verbose explanations when libs are missing.

**Comment by xoltar** [comment]
Hi Folks, 

I'd suggest that the main issue here is that it's hard for a new user to tell what's a problem and what's not. So for example I'd recommend changing ERROR to WARNING in the following text:

```
ERROR: The following packages.failed.install: ssl
readline
bdb
```
Also, probably better to hide the `QA Notice` warning entirely by default, since it sounds very dire. The warnings in the final wrap-up screen are fine, and if it hadn't been for the ERROR above and QA Notice I probably would have tried using the system rather than posting a bug report.

Thanks for working on this!
Bryn

**Comment by fnogatz** [comment]
@JanWielemaker, maybe this is worth considering for SWI-Prolog?

**Comment by JanWielemaker** [comment]
In any case, as we moved to CMake the old diagnostics are no longer relevant.   How to handle (partially) broken installation and feedback on the result using CMake should be is another issue.
At the moment `?- check_installation.` does not run for the CMake build.  Not sure how to restore that.
Should we try?

**Comment by fnogatz** [comment]
Closing this. The installation of `v7.7.16` seems to be okay, and the other things are more related to SWI-Prolog in general.
