### ISSUE TITLE
cmake

### ISSUE THREAD

**Issue by Anniepoo** [fnogatz/swivm#11]
with a brand new Ubuntu 18.04 install, swivm fails to install the cmake dependencies if you use the list of dependencies in the readme.

anniepoo@annieslaptop:~$ swivm install 7.7.23
Downloading http://www.swi-prolog.org/download/devel/src/swipl-7.7.23.tar.gz...
######################################################################### 100.0%

Command 'cmake' not found, but can be installed with:

sudo apt install cmake

### [SWIVM] Prepare Installation Template ###

Done on a fresh 18.04 install, after copy/pasting the dependency list from the readme

**Comment by fnogatz** [comment]
Solved via #13.
