### ISSUE TITLE
making an alias

### ISSUE THREAD

**Issue by Anniepoo** [fnogatz/swivm#18]
appears to be broken

anniepoo@annieslaptop:\~/work/terminus-server$ swivm alias 
default -> 8.1.14
stable -> 8.0.3
devel -> 8.1 (-> 8.1.14) (default)
anniepoo@annieslaptop:\~/work/terminus-server$ swivm use stable
N/A: version "stable -> " is not yet installed
anniepoo@annieslaptop:\~/work/terminus-server$ swivm alias stable 8.0.3
stable -> 8.0.3
anniepoo@annieslaptop:\~/work/terminus-server$ swivm use stable
N/A: version "stable -> " is not yet installed
anniepoo@annieslaptop:\~/work/terminus-server$ swivm use 8.0.3
Now using SWI-Prolog 8.0.3
anniepoo@annieslaptop:\~/work/terminus-server$

**Comment by fnogatz** [comment]
Hi Anne, thank you for the bug report. I adopted several changes from the latest [nvm](https://github.com/nvm-sh/nvm) and published a new version 1.0 of swivm. Please note that I changed the path of versions, so you have to rename existing directories according [to the README](https://github.com/fnogatz/swivm#migration-from-v0x-to-v1x).

**Comment by fnogatz** [comment]
`swivm alias`, `swivm unalias`, and the others are working again in v1.0, so I'm closing this issue here.
