### ISSUE TITLE
ls-remote and other commands fail on MacOS X

### ISSUE THREAD

**Issue by xoltar** [fnogatz/swivm#9]
With High Sierra, 'swivm ls-remote' or any attempt to install a version give errors that 'r' is not a recognized argument for sed.

This is caused by differences in MacOS X sed and GNU sed.

**Workaround:** `brew install gnu-sed`, then create a symlink to 'gsed' (but that you name 'sed') that appears earlier in your PATH than /usr/bin/sed (e.g. in my case I used ~/.local/bin).

**Comment by fnogatz** [comment]
I just uploaded v0.3.4 which changes the `sed` commands to use flags which are compatible for both gnu-sed and the Mac OS version (see #7). Is `swim ls-remote` working again?

**Comment by xoltar** [comment]
I removed the old install, ran `curl -o-
https://raw.githubusercontent.com/fnogatz/swivm/v0.3.4/install.sh | bash`
to install the new. It looks like it installed 0.3.2 despite asking for
0.3.4:

```
> $ curl -o-
https://raw.githubusercontent.com/fnogatz/swivm/v0.3.4/install.sh |
bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time
Current
                                 Dload  Upload   Total   Spent    Left
Speed
100  6590  100  6590    0     0  29579      0 --:--:-- --:--:-- --:--:--
29684
=> Downloading swivm from git to '/Users/bkeller/.swivm'
=> Cloning into '/Users/bkeller/.swivm'...
remote: Counting objects: 4273, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 4273 (delta 16), reused 23 (delta 11), pack-reused 4245
Receiving objects: 100% (4273/4273), 1.05 MiB | 5.86 MiB/s, done.
Resolving deltas: 100% (2530/2530), done.
* (HEAD detached at v0.3.2)
  master
```

Both the version it installed and master still have the same behavior:

```
> $ swivm
ls-remote
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ...
[file ...]
            N/A
```

**Comment by xoltar** [comment]
I removed the old install, ran `curl -o- https://raw.githubusercontent.com/fnogatz/swivm/v0.3.4/install.sh | bash`
to install the new. It looks like it installed 0.3.2 despite asking for
0.3.4:

```
> $ curl -o-
https://raw.githubusercontent.com/fnogatz/swivm/v0.3.4/install.sh |
bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time
Current
                                 Dload  Upload   Total   Spent    Left
Speed
100  6590  100  6590    0     0  29579      0 --:--:-- --:--:-- --:--:--
29684
=> Downloading swivm from git to '/Users/bkeller/.swivm'
=> Cloning into '/Users/bkeller/.swivm'...
remote: Counting objects: 4273, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 4273 (delta 16), reused 23 (delta 11), pack-reused 4245
Receiving objects: 100% (4273/4273), 1.05 MiB | 5.86 MiB/s, done.
Resolving deltas: 100% (2530/2530), done.
* (HEAD detached at v0.3.2)
  master
```

Both the version it installed and master still have the same behavior:

```
> $ swivm
ls-remote
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ...
[file ...]
            N/A
```

**Comment by fnogatz** [comment]
Oops, you are right - the `sed -r/-E` changes are only available in version `0.3.5`.

**Comment by fnogatz** [comment]
Is this working again with some of the versions higher than `0.3.4`?

**Comment by xoltar** [comment]
Yes, it works with v0.3.5 and above for me. Thanks!

**Comment by fnogatz** [comment]
Okay, thank you for reporting this. I will close the issue here.
